### ISSUE TITLE
[BUG] Root mapping definition has unsupported parameters

### ISSUE THREAD

**Issue by Findthelorax** [linuxserver/docker-diskover#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CRITICAL - FATAL ERROR: an exception has occurred: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:

### Expected Behavior

i believe it should start a crawl on my data

### Steps To Reproduce

1. installed elasticsearch
2. installed diskover
3. both are on custom networks
4. ran sysctl -w vm.max_map_count=262144
5. docker exec -u abc -it diskover python3 /app/diskover/diskover.py -i diskover-my_instalce_name /data

### Environment

```markdown
- OS: unraid 6.11.5
- How docker service was installed: unraid ca manager
```

### CPU architecture

x86-64

### Docker creation

```bash
installed via unraid
```

### Container logs

```bash
2023-05-20 08:50:25,166 - diskover - INFO - Config file: /config/diskover.conf.d/diskover/config.yaml
2023-05-20 08:50:25,166 - diskover - INFO - Config env var DISKOVERDIR: /config/diskover.conf.d/diskover/
2023-05-20 08:50:25,166 - diskover - INFO - No plugins loaded
2023-05-20 08:50:25,166 - diskover - INFO - No plugins loaded
2023-05-20 08:50:25,166 - diskover - INFO - Creating index diskover-elasticsearch...
2023-05-20 08:50:25,183 - elasticsearch - WARNING - PUT http://10.0.0.13:9201/diskover-elasticsearch [status:400 request:0.014s]
2023-05-20 08:50:25,183 - diskover - CRITICAL - FATAL ERROR: an exception has occurred: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [end_at : {type=date}] [extension : {type=keyword}] [free_percent : {type=float}] [available : {type=long}] [used : {type=long}] [mtime : {type=date}] [start_at : {type=date}] [type : {type=keyword}] [diskover_ver : {type=keyword}] [size_du : {type=long}] [path : {type=keyword}] [crawl_time : {type=float}] [dir_count_norecurs : {type=long}] [total : {type=long}] [size_norecurs : {type=long}] [file_count_norecurs : {type=long}] [ctime : {type=date}] [parent_path : {type=keyword, fields={text={analyzer=path_analyzer, type=text}}}] [free : {type=long}] [group : {type=keyword}] [file_count : {type=long}] [owner : {type=keyword}] [atime : {type=date}] [available_percent : {type=float}] [nlink : {type=integer}] [size_du_norecurs : {type=long}] [ino : {type=keyword}] [file_size_du : {type=long}] [file_size : {type=long}] [size : {type=long}] [name : {type=keyword, fields={text={analyzer=filename_analyzer, type=text}}}] [dir_depth : {type=integer}] [dir_count : {type=long}]')
Traceback (most recent call last):
  File "/app/diskover/diskover.py", line 1236, in <module>
    create_index(options.index, es)
  File "/app/diskover/diskover_elasticsearch.py", line 420, in create_index
    es.indices.create(index=indexname, body=mappings)
  File "/usr/lib/python3.10/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/lib/python3.10/site-packages/elasticsearch/client/indices.py", line 123, in create
    return self.transport.perform_request(
  File "/usr/lib/python3.10/site-packages/elasticsearch/transport.py", line 415, in perform_request
    raise e
  File "/usr/lib/python3.10/site-packages/elasticsearch/transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/lib/python3.10/site-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python3.10/site-packages/elasticsearch/connection/base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [end_at : {type=date}] [extension : {type=keyword}] [free_percent : {type=float}] [available : {type=long}] [used : {type=long}] [mtime : {type=date}] [start_at : {type=date}] [type : {type=keyword}] [diskover_ver : {type=keyword}] [size_du : {type=long}] [path : {type=keyword}] [crawl_time : {type=float}] [dir_count_norecurs : {type=long}] [total : {type=long}] [size_norecurs : {type=long}] [file_count_norecurs : {type=long}] [ctime : {type=date}] [parent_path : {type=keyword, fields={text={analyzer=path_analyzer, type=text}}}] [free : {type=long}] [group : {type=keyword}] [file_count : {type=long}] [owner : {type=keyword}] [atime : {type=date}] [available_percent : {type=float}] [nlink : {type=integer}] [size_du_norecurs : {type=long}] [ino : {type=keyword}] [file_size_du : {type=long}] [file_size : {type=long}] [size : {type=long}] [name : {type=keyword, fields={text={analyzer=filename_analyzer, type=text}}}] [dir_depth : {type=integer}] [dir_count : {type=long}]')
2023-05-20 08:50:25,186 - diskover - CRITICAL - CRITICAL ERROR EXITING
```

SOLVED: permissions issue, installed d8sychain/elasticsearch and had to run:
 sudo chown -R 1000:0 /mnt/user/appdata/elasticsearch

**Comment by Findthelorax** [comment]
sudo chown -R 1000:0 /mnt/user/appdata/elasticsearcher
